[build]
  command = "" # site statique
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Force Netlify Forms à rediriger vers ta page de remerciement custom
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# (Optionnel) empêcher la page /admin.html d’être indexée
[[headers]]
  for = "/admin.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
